# Generated by Django 4.2.18 on 2025-02-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=22, null=True)),
                ('product_price', models.PositiveIntegerField(default=0, null=True)),
                ('product_quantity', models.PositiveIntegerField(default=0, null=True)),
                ('product_period', models.DateField(auto_now=True)),
            ],
        ),
    ]
