# Generated by Django 4.2.18 on 2025-02-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_table',
            old_name='product_name',
            new_name='productname',
        ),
    ]
