# Generated by Django 4.2.18 on 2025-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_rename_product_name_stock_table_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_table',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
